name: Build Enterwait System

on:
  push:
    branches:
      - main
      - stg
      - dev
    paths:
      - 'enterwait/**'

env:
  AWS_REGION: ap-northeast-2

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::159960117927:role/github-actions-aws-credentials
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push docker image to Amazon ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: enterwait-${{ github.ref_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          cd enterwait
          docker build -t ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG} .
          docker push ${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}
